### ISSUE TITLE
[ERROR] unknown option in "*.fasta"

### ISSUE THREAD

**Issue by katholan** [JanaSperschneider/NuclearPhaser#10]
Hello,

I have been working on running this pipeline for the past few days. I have made the required files, installed the required packages, but when running NuclearPhaser.py, it keeps outputting the error "unknown option in *.fasta". I also tried with the Toy Example provided with this repository in case it was something wrong with my files, but this returned the same error, as shown below. 

```
cd ToyExample/
unzip genome_example.zip

python ../NuclearPhaser.py -g GeneHits_genome_example.txt -b full_table_buscov3_genome_example.tsv -c HiC_MAPQ30.genome_example.20000.matrix.tsv -f genome_example.fasta -o test
Run minimap2
[ERROR] unknown option in "genome_example.fasta"
```

The command creates the output folder 'test' with an empty subfolder 'Plots', with no other files.

Any insight into what may be causing the error would be much appreciated!
Kat

**Comment by JanaSperschneider** [comment]
Hi Kat,

sorry to hear the pipeline isn't running smoothly... I tried to re-produce the error message but couldn't. Steps I ran are:

- I downloaded the latest release 1.1 under 'Releases' (https://github.com/JanaSperschneider/NuclearPhaser/releases)
- I unzipped the release

Then I ran:

```
cd ToyExample/
unzip genome_example.zip
python ../NuclearPhaser.py -g GeneHits_genome_example.txt -b full_table_buscov3_genome_example.tsv -c HiC_MAPQ30.genome_example.20000.matrix.tsv -f genome_example.fasta -o test
```

```
Run minimap2
[M::mm_idx_gen::0.763*1.03] collected minimizers
[M::mm_idx_gen::0.855*1.23] sorted minimizers
[M::main::0.855*1.23] loaded/built the index for 52 target sequence(s)
[M::mm_mapopt_update::0.886*1.23] mid_occ = 91
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 52
[M::mm_idx_stat::0.907*1.22] distinct minimizers: 2279828 (20.90% are singletons); average occurrences: 2.267; average spacing: 9.994; total length: 51644244
[M::worker_pipeline::6.660*2.32] mapped 52 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -k19 -w19 -m200 -DP -r1000 -o test/temp.paf genome_example.fasta genome_example.fasta
[M::main] Real time: 6.670 sec; CPU: 15.449 sec; Peak RSS: 0.895 GB
Minimap2 alignments are finished, now scan the paf file.
Done scanning the PAF alignment file.
Now find haplotigs
Mean alignment length is: 15189.602808211892
Find contig pairs that share genes.
Read in contact map
Hi-C contact matrix has resolution: 20000
Done
Construct graph from contig pairs to find well-connected groups
Construct community
Use 5 gene bins.

Contigs in bins: 51 with a total length of 51.612912 MB
Still unphased: 1 contigs with a total length of 0.031332 MB

Construct graph to phase the gene bins with Hi-C trans contact data

Construct community to phase gene bins into the haplotypes
```

Can you try and repeat this and let me know if you still have a problem?

Thanks!
Jana

**Comment by katholan** [comment]
Hi Jana,

Thanks for taking the time to help! I re-downloaded the latest release and tried again but got the same error. I also tried creating a new conda environment and that worked for the Toy Example and seems to be running so far on my own data! So I suppose something was wrong with the environment I was using.

Thanks again for your help!
Kat
